# Generated by Django 4.2.7 on 2023-12-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('organization', models.CharField(blank=True, max_length=50, null=True, verbose_name='Организация')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('place_residense', models.DateField(blank=True, null=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.contact')),
            ],
        ),
    ]
