# Generated by Django 4.2.7 on 2023-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='repeat_id',
            field=models.IntegerField(null=True),
        ),
    ]
