# Generated by Django 4.2.7 on 2023-12-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registration', models.DateField(verbose_name='Дата постановки на учет')),
                ('descripion', models.TextField(verbose_name='Описание')),
                ('type_property', models.CharField(choices=[('Трактор', 'Трактор'), ('Вертолет', 'Вертолет'), ('Прицеп', 'Прицеп'), ('Трицикл', 'Трицикл'), ('Автомобиль', 'Автомобиль'), ('Самолет', 'Самолет'), ('Квадроцикл', 'Квадроцикл'), ('Автобус', 'Автобус'), ('Катер', 'Катер'), ('Мотоцикл', 'Мотоцикл')], default='Автомобиль', max_length=12, verbose_name='Тип транспортного средства')),
                ('brand', models.CharField(max_length=16, verbose_name='Марка ТС')),
                ('model', models.CharField(max_length=16, verbose_name='Модель ТС')),
                ('year_release', models.CharField(max_length=4, verbose_name='Год выпуска ТС')),
                ('power_engine', models.IntegerField(blank=True, null=True, verbose_name='Мощность двигателя, л.с.')),
                ('weigth', models.IntegerField(blank=True, null=True, verbose_name='Масса ТС, кг')),
                ('carrying', models.IntegerField(blank=True, null=True, verbose_name='Грузоподъемность, кг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'property_app_transport',
            },
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registration', models.DateField(verbose_name='Дата постановки на учет')),
                ('descripion', models.TextField(verbose_name='Описание')),
                ('type_property', models.CharField(choices=[('Складское помещений', 'Складское помещение'), ('Земельный участок', 'Земельный участок'), ('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Гараж', 'Гараж')], default='Квартира', max_length=20, verbose_name='Тип недвижимости')),
                ('cadastral_number', models.CharField(max_length=24, verbose_name='Кадастровый номер')),
                ('cadastral_cost', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Кадастровая стоимость, руб.')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес расположения')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь, кв.м.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'property_app_realty',
            },
        ),
    ]
