# Generated by Django 4.2.7 on 2023-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realty',
            old_name='descripion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='transport',
            name='registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='type_property',
            field=models.CharField(choices=[('Складское помещений', 'Складское помещение'), ('Дом', 'Дом'), ('Гараж', 'Гараж'), ('Земельный участок', 'Земельный участок'), ('Квартира', 'Квартира')], default='Квартира', max_length=20, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='carrying',
            field=models.IntegerField(blank=True, null=True, verbose_name='Грузоподъемность ТС, кг'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type_property',
            field=models.CharField(choices=[('Вертолет', 'Вертолет'), ('Самолет', 'Самолет'), ('Трактор', 'Трактор'), ('Мотоцикл', 'Мотоцикл'), ('Квадроцикл', 'Квадроцикл'), ('Катер', 'Катер'), ('Трицикл', 'Трицикл'), ('Прицеп', 'Прицеп'), ('Автомобиль', 'Автомобиль'), ('Автобус', 'Автобус')], default='Автомобиль', max_length=12, verbose_name='Тип транспортного средства'),
        ),
    ]
