# Generated by Django 4.2.7 on 2023-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_rename_descripion_realty_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='type_property',
            field=models.CharField(choices=[('Гараж', 'Гараж'), ('Дом', 'Дом'), ('Земельный участок', 'Земельный участок'), ('Квартира', 'Квартира'), ('Складское помещений', 'Складское помещение')], default='Квартира', max_length=20, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type_property',
            field=models.CharField(choices=[('Автобус', 'Автобус'), ('Автомобиль', 'Автомобиль'), ('Вертолет', 'Вертолет'), ('Катер', 'Катер'), ('Квадроцикл', 'Квадроцикл'), ('Мотоцикл', 'Мотоцикл'), ('Прицеп', 'Прицеп'), ('Самолет', 'Самолет'), ('Трактор', 'Трактор'), ('Трицикл', 'Трицикл')], default='Автомобиль', max_length=12, verbose_name='Тип транспортного средства'),
        ),
    ]
