# Generated by Django 4.2.7 on 2023-12-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('hash_password', models.BinaryField()),
                ('salt', models.BinaryField()),
            ],
            options={
                'db_table': 'user_app_user',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7, null=True, verbose_name='Пол')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место рождения')),
                ('place_residense', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место жительства')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_app.user')),
            ],
            options={
                'db_table': 'user_app_data',
            },
        ),
    ]
