# Generated by Django 4.2.6 on 2023-12-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0002_alter_militaryticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryticket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные сведения'),
        ),
        migrations.AlterField(
            model_name='militaryticket',
            name='speciality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Военная специальность'),
        ),
    ]
