# Generated by Django 4.2.7 on 2023-12-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, null=True, verbose_name='Серия')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('date_registration', models.DateField(verbose_name='Дата выдачи')),
                ('name', models.CharField(choices=[('Аттестат', 'Аттестат'), ('Диплом', 'Диплом'), ('Свидетельство', 'Свидетельство'), ('Сертификат', 'Сертификат')], default='Диплом', max_length=50, verbose_name='Вид документа')),
                ('registration_number', models.IntegerField(blank=True, null=True, verbose_name='Регистрационный номер')),
                ('name_institution', models.CharField(max_length=100, verbose_name='Название учебного заведения')),
                ('year_of_start_edu', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год начала обучения')),
                ('year_of_finish_edu', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год окончания обучения')),
                ('spiciality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Специальность')),
                ('spicialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Специализация')),
                ('description', models.TextField(verbose_name='Дополнительные сведения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'db_table': 'education_app_diploma',
            },
        ),
    ]
