# Generated by Django 4.2.7 on 2023-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные сведения'),
        ),
    ]
