# Generated by Django 4.2.6 on 2023-12-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0002_alter_diploma_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='year_of_finish_edu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год окончания обучения'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='year_of_start_edu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год начала обучения'),
        ),
    ]
